CREATE TABLE departments (
  department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  department_name VARCHAR2(100) NOT NULL,
  PRIMARY KEY (department_id)
);

CREATE TABLE job_titles (
  job_title_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  job_title VARCHAR2(100) NOT NULL,
  PRIMARY KEY (job_title_id)
);

CREATE TABLE employees (
  employee_id NUMBER PRIMARY KEY,
  full_name VARCHAR2(100),
  department_id NUMBER,
  job_title_id NUMBER,
  gender VARCHAR2(10),
  ethnicity VARCHAR2(50),
  age NUMBER,
  hire_date DATE,
  country VARCHAR2(50),
  city VARCHAR2(50),
  exit_date DATE,
  FOREIGN KEY (department_id) REFERENCES departments(department_id),
  FOREIGN KEY (job_title_id) REFERENCES job_titles(job_title_id)
);

CREATE TABLE salaries (
  salary_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id NUMBER,
  annual_salary NUMBER,
  bonus_percent NUMBER,
  effective_date DATE,
  FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
);
