CREATE SEQUENCE employee_id_seq
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE departments_id_seq
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE positions_id_seq
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE salary_id_seq
START WITH 1
INCREMENT BY 1
NOCACHE;